# -*- coding: utf-8 -*-
DIVISAS = (
    ('', '------'),
    (u'PEN - S/.', 'Nuevo sol'),
    (u'USD - $', 'Dolar americano'),
    (u'EUR - €', 'Euro')
)

ESTRELLAS = (
		(1,"1"),
		(2,"2"),
		(3,"3"),
		(4,"4"),
		(5,"5"),
	)

RQ = (
		("Reclamo","Reclamo"),
		("Queja","Queja")
	)

IDI = (
		(u"Español","Español"),
		(u"Ingles","Ingles")
	)

DOCS_IDENT = (
		("DNI","DNI"),
		("Carnet de extranjería","Carnet de extranjería")
	)

PAISES_GLOBAL_ES = (
		(u'Afganistán',u'Afganistán'),
		(u'Albania',u'Albania'),
		(u'Alemania',u'Alemania'),
		(u'Andorra',u'Andorra'),
		(u'Angola',u'Angola'),
		(u'Antigua y Barbuda',u'Antigua y Barbuda'),
		(u'Arabia Saudita',u'Arabia Saudita'),
		(u'Argelia',u'Argelia'),
		(u'Argentina',u'Argentina'),
		(u'Armenia',u'Armenia'),
		(u'Australia',u'Australia'),
		(u'Austria',u'Austria'),
		(u'Azerbaiyán',u'Azerbaiyán'),
		(u'Bahamas',u'Bahamas'),
		(u'Bangladés',u'Bangladés'),
		(u'Barbados',u'Barbados'),
		(u'Baréin',u'Baréin'),
		(u'Bélgica',u'Bélgica'),
		(u'Belice',u'Belice'),
		(u'Benín',u'Benín'),
		(u'Bielorrusia',u'Bielorrusia'),
		(u'Birmania',u'Birmania'),
		(u'Bolivia',u'Bolivia'),
		(u'Bosnia y Herzegovina',u'Bosnia y Herzegovina'),
		(u'Botsuana',u'Botsuana'),
		(u'Brasil',u'Brasil'),
		(u'Brunéi',u'Brunéi'),
		(u'Bulgaria',u'Bulgaria'),
		(u'Burkina Faso',u'Burkina Faso'),
		(u'Burundi',u'Burundi'),
		(u'Bután',u'Bután'),
		(u'Cabo Verde',u'Cabo Verde'),
		(u'Camboya',u'Camboya'),
		(u'Camerún',u'Camerún'),
		(u'Canadá',u'Canadá'),
		(u'Catar',u'Catar'),
		(u'Chad',u'Chad'),
		(u'Chile',u'Chile'),
		(u'China',u'China'),
		(u'Chipre',u'Chipre'),
		(u'Ciudad del Vaticano',u'Ciudad del Vaticano'),
		(u'Colombia',u'Colombia'),
		(u'Comoras',u'Comoras'),
		(u'Corea del Norte',u'Corea del Norte'),
		(u'Corea del Sur',u'Corea del Sur'),
		(u'Costa de Marfil',u'Costa de Marfil'),
		(u'Costa Rica',u'Costa Rica'),
		(u'Croacia',u'Croacia'),
		(u'Cuba',u'Cuba'),
		(u'Dinamarca',u'Dinamarca'),
		(u'Dominica',u'Dominica'),
		(u'Ecuador',u'Ecuador'),
		(u'Egipto',u'Egipto'),
		(u'El Salvador',u'El Salvador'),
		(u'Emiratos Árabes Unidos',u'Emiratos Árabes Unidos'),
		(u'Eritrea',u'Eritrea'),
		(u'Eslovaquia',u'Eslovaquia'),
		(u'Eslovenia',u'Eslovenia'),
		(u'España',u'España'),
		(u'Estados Unidos',u'Estados Unidos'),
		(u'Estonia',u'Estonia'),
		(u'Etiopía',u'Etiopía'),
		(u'Filipinas',u'Filipinas'),
		(u'Finlandia',u'Finlandia'),
		(u'Fiyi',u'Fiyi'),
		(u'Francia',u'Francia'),
		(u'Gabón',u'Gabón'),
		(u'Gambia',u'Gambia'),
		(u'Georgia',u'Georgia'),
		(u'Ghana',u'Ghana'),
		(u'Granada',u'Granada'),
		(u'Grecia',u'Grecia'),
		(u'Guatemala',u'Guatemala'),
		(u'Guyana',u'Guyana'),
		(u'Guinea',u'Guinea'),
		(u'Guinea ecuatorial',u'Guinea ecuatorial'),
		(u'Guinea-Bisáu',u'Guinea-Bisáu'),
		(u'Haití',u'Haití'),
		(u'Honduras',u'Honduras'),
		(u'Hungría',u'Hungría'),
		(u'India',u'India'),
		(u'Indonesia',u'Indonesia'),
		(u'Irak',u'Irak'),
		(u'Irán',u'Irán'),
		(u'Irlanda',u'Irlanda'),
		(u'Islandia',u'Islandia'),
		(u'Islas Marshall',u'Islas Marshall'),
		(u'Islas Salomón',u'Islas Salomón'),
		(u'Israel',u'Israel'),
		(u'Italia',u'Italia'),
		(u'Jamaica',u'Jamaica'),
		(u'Japón',u'Japón'),
		(u'Jordania',u'Jordania'),
		(u'Kazajistán',u'Kazajistán'),
		(u'Kenia',u'Kenia'),
		(u'Kirguistán',u'Kirguistán'),
		(u'Kiribati',u'Kiribati'),
		(u'Kuwait',u'Kuwait'),
		(u'Laos',u'Laos'),
		(u'Lesoto',u'Lesoto'),
		(u'Letonia',u'Letonia'),
		(u'Líbano',u'Líbano'),
		(u'Liberia',u'Liberia'),
		(u'Libia',u'Libia'),
		(u'Liechtenstein',u'Liechtenstein'),
		(u'Lituania',u'Lituania'),
		(u'Luxemburgo',u'Luxemburgo'),
		(u'Madagascar',u'Madagascar'),
		(u'Malasia',u'Malasia'),
		(u'Malaui',u'Malaui'),
		(u'Maldivas',u'Maldivas'),
		(u'Malí',u'Malí'),
		(u'Malta',u'Malta'),
		(u'Marruecos',u'Marruecos'),
		(u'Mauricio',u'Mauricio'),
		(u'Mauritania',u'Mauritania'),
		(u'México',u'México'),
		(u'Micronesia',u'Micronesia'),
		(u'Moldavia',u'Moldavia'),
		(u'Mónaco',u'Mónaco'),
		(u'Mongolia',u'Mongolia'),
		(u'Montenegro',u'Montenegro'),
		(u'Mozambique',u'Mozambique'),
		(u'Namibia',u'Namibia'),
		(u'Nauru',u'Nauru'),
		(u'Nepal',u'Nepal'),
		(u'Nicaragua',u'Nicaragua'),
		(u'Níger',u'Níger'),
		(u'Nigeria',u'Nigeria'),
		(u'Noruega',u'Noruega'),
		(u'Nueva Zelanda',u'Nueva Zelanda'),
		(u'Omán',u'Omán'),
		(u'Países Bajos',u'Países Bajos'),
		(u'Pakistán',u'Pakistán'),
		(u'Palaos',u'Palaos'),
		(u'Panamá',u'Panamá'),
		(u'Papúa Nueva Guinea',u'Papúa Nueva Guinea'),
		(u'Paraguay',u'Paraguay'),
		(u'Perú',u'Perú'),
		(u'Polonia',u'Polonia'),
		(u'Portugal',u'Portugal'),
		(u'Reino Unido',u'Reino Unido'),
		(u'República Centroafricana',u'República Centroafricana'),
		(u'República Checa',u'República Checa'),
		(u'República de Macedonia',u'República de Macedonia'),
		(u'República del Congo',u'República del Congo'),
		(u'República Democrática del Congo',u'República Democrática del Congo'),
		(u'República Dominicana',u'República Dominicana'),
		(u'República Sudafricana',u'República Sudafricana'),
		(u'Ruanda',u'Ruanda'),
		(u'Rumanía',u'Rumanía'),
		(u'Rusia',u'Rusia'),
		(u'Samoa',u'Samoa'),
		(u'San Cristóbal y Nieves',u'San Cristóbal y Nieves'),
		(u'San Marino',u'San Marino'),
		(u'San Vicente y las Granadinas',u'San Vicente y las Granadinas'),
		(u'Santa Lucía',u'Santa Lucía'),
		(u'Santo Tomé y Príncipe',u'Santo Tomé y Príncipe'),
		(u'Senegal',u'Senegal'),
		(u'Serbia',u'Serbia'),
		(u'Seychelles',u'Seychelles'),
		(u'Sierra Leona',u'Sierra Leona'),
		(u'Singapur',u'Singapur'),
		(u'Siria',u'Siria'),
		(u'Somalia',u'Somalia'),
		(u'Sri Lanka',u'Sri Lanka'),
		(u'Suazilandia',u'Suazilandia'),
		(u'Sudán',u'Sudán'),
		(u'Sudán del Sur',u'Sudán del Sur'),
		(u'Suecia',u'Suecia'),
		(u'Suiza',u'Suiza'),
		(u'Surinam',u'Surinam'),
		(u'Tailandia',u'Tailandia'),
		(u'Tanzania',u'Tanzania'),
		(u'Tayikistán',u'Tayikistán'),
		(u'Timor Oriental',u'Timor Oriental'),
		(u'Togo',u'Togo'),
		(u'Tonga',u'Tonga'),
		(u'Trinidad y Tobago',u'Trinidad y Tobago'),
		(u'Túnez',u'Túnez'),
		(u'Turkmenistán',u'Turkmenistán'),
		(u'Turquía',u'Turquía'),
		(u'Tuvalu',u'Tuvalu'),
		(u'Ucrania',u'Ucrania'),
		(u'Uganda',u'Uganda'),
		(u'Uruguay',u'Uruguay'),
		(u'Uzbekistán',u'Uzbekistán'),
		(u'Vanuatu',u'Vanuatu'),
		(u'Venezuela',u'Venezuela'),
		(u'Vietnam',u'Vietnam'),
		(u'Yemen',u'Yemen'),
		(u'Yibuti',u'Yibuti'),
		(u'Zambia',u'Zambia'),
		(u'Zimbabue',u'Zimbabue')

	)


PAISES_GLOBAL_EN = (
		(u'Afghanistan',u'Afghanistan'),
		(u'Albania',u'Albania'),
		(u'Algeria',u'Algeria'),
		(u'Andorra',u'Andorra'),
		(u'Angola',u'Angola'),
		(u'Antigua and Barbuda',u'Antigua and Barbuda'),
		(u'Argentina',u'Argentina'),
		(u'Armenia',u'Armenia'),
		(u'Australia',u'Australia'),
		(u'Austria',u'Austria'),
		(u'Azerbaijan',u'Azerbaijan'),
		(u'Bahamas, The',u'Bahamas, The'),
		(u'Bahrain',u'Bahrain'),
		(u'Bangladesh',u'Bangladesh'),
		(u'Barbados',u'Barbados'),
		(u'Belarus',u'Belarus'),
		(u'Belgium',u'Belgium'),
		(u'Belize',u'Belize'),
		(u'Benin',u'Benin'),
		(u'Bhutan',u'Bhutan'),
		(u'Bolivia',u'Bolivia'),
		(u'Bosnia and Herzegovina',u'Bosnia and Herzegovina'),
		(u'Botswana',u'Botswana'),
		(u'Brazil',u'Brazil'),
		(u'Britain',u'Britain'),
		(u'Brunei',u'Brunei'),
		(u'Bulgaria',u'Bulgaria'),
		(u'Burkina Faso',u'Burkina Faso'),
		(u'Burundi',u'Burundi'),
		(u'Cambodia',u'Cambodia'),
		(u'Cameroon',u'Cameroon'),
		(u'Canada',u'Canada'),
		(u'Cape Verde',u'Cape Verde'),
		(u'Central African Republic',u'Central African Republic'),
		(u'Chad',u'Chad'),
		(u'Chile',u'Chile'),
		(u'China',u'China'),
		(u'Colombia',u'Colombia'),
		(u'Comoros',u'Comoros'),
		(u'Congo, Democratic Republic of the',u'Congo, Democratic Republic of the'),
		(u'Costa Rica',u'Costa Rica'),
		(u"Cote D'Ivoire",u"Cote D'Ivoire"),
		(u'Croatia',u'Croatia'),
		(u'Cuba',u'Cuba'),
		(u'Cyprus',u'Cyprus'),
		(u'Czech Republic',u'Czech Republic'),
		(u'Czechoslovakia',u'Czechoslovakia'),
		(u'Denmark',u'Denmark'),
		(u'Djibouti',u'Djibouti'),
		(u'Dominica',u'Dominica'),
		(u'Dominican Republic',u'Dominican Republic'),
		(u'Ecuador',u'Ecuador'),
		(u'Egypt',u'Egypt'),
		(u'El Salvador',u'El Salvador'),
		(u'England',u'England'),
		(u'Equatorial Guinea',u'Equatorial Guinea'),
		(u'Eritrea',u'Eritrea'),
		(u'Estonia',u'Estonia'),
		(u'Ethiopia',u'Ethiopia'),
		(u'Fiji',u'Fiji'),
		(u'Finland',u'Finland'),
		(u'France',u'France'),
		(u'Gabon',u'Gabon'),
		(u'Gambia, The',u'Gambia, The'),
		(u'Georgia',u'Georgia'),
		(u'Germany',u'Germany'),
		(u'Ghana',u'Ghana'),
		(u'Great Britain',u'Great Britain'),
		(u'Greece',u'Greece'),
		(u'Greenland',u'Greenland'),
		(u'Grenada',u'Grenada'),
		(u'Guatemala',u'Guatemala'),
		(u'Guinea',u'Guinea'),
		(u'Guinea-Bissau',u'Guinea-Bissau'),
		(u'Guyana',u'Guyana'),
		(u'Haiti',u'Haiti'),
		(u'Honduras',u'Honduras'),
		(u'Hungary',u'Hungary'),
		(u'Iceland',u'Iceland'),
		(u'India',u'India'),
		(u'Indonesia',u'Indonesia'),
		(u'Iran',u'Iran'),
		(u'Iraq',u'Iraq'),
		(u'Ireland',u'Ireland'),
		(u'Ireland, Northern',u'Ireland, Northern'),
		(u'Israel',u'Israel'),
		(u'Italy',u'Italy'),
		(u'Jamaica',u'Jamaica'),
		(u'Japan',u'Japan'),
		(u'Java',u'Java'),
		(u'Jordan',u'Jordan'),
		(u'Kazakhstan',u'Kazakhstan'),
		(u'Kenya',u'Kenya'),
		(u'Kiribati',u'Kiribati'),
		(u'Korea, North',u'Korea, North'),
		(u'Korea, South',u'Korea, South'),
		(u'Kuwait',u'Kuwait'),
		(u'Kyrgyzstan',u'Kyrgyzstan'),
		(u'Laos',u'Laos'),
		(u'Latvia',u'Latvia'),
		(u'Lebanon',u'Lebanon'),
		(u'Lesotho',u'Lesotho'),
		(u'Liberia',u'Liberia'),
		(u'Libya',u'Libya'),
		(u'Liechtenstein',u'Liechtenstein'),
		(u'Lithuania',u'Lithuania'),
		(u'Luxembourg',u'Luxembourg'),
		(u'Macedonia',u'Macedonia'),
		(u'Madagascar',u'Madagascar'),
		(u'Malawi',u'Malawi'),
		(u'Malaysia',u'Malaysia'),
		(u'Maldives',u'Maldives'),
		(u'Mali',u'Mali'),
		(u'Malta',u'Malta'),
		(u'Marshall Islands',u'Marshall Islands'),
		(u'Mauritania',u'Mauritania'),
		(u'Mauritius',u'Mauritius'),
		(u'Mexico',u'Mexico'),
		(u'Micronesia',u'Micronesia'),
		(u'Moldova',u'Moldova'),
		(u'Monaco',u'Monaco'),
		(u'Mongolia',u'Mongolia'),
		(u'Morocco',u'Morocco'),
		(u'Mozambique',u'Mozambique'),
		(u'Myanmar (Burma)',u'Myanmar (Burma)'),
		(u'Namibia',u'Namibia'),
		(u'Nauru',u'Nauru'),
		(u'Nepal',u'Nepal'),
		(u'Netherlands, The',u'Netherlands, The'),
		(u'New Zealand',u'New Zealand'),
		(u'Nicaragua',u'Nicaragua'),
		(u'Niger',u'Niger'),
		(u'Nigeria',u'Nigeria'),
		(u'North Korea',u'North Korea'),
		(u'Norway',u'Norway'),
		(u'Northern Ireland',u'Northern Ireland'),
		(u'Oman',u'Oman'),
		(u'Pakistan',u'Pakistan'),
		(u'Palau',u'Palau'),
		(u'Panama',u'Panama'),
		(u'Papua New Guinea',u'Papua New Guinea'),
		(u'Paraguay',u'Paraguay'),
		(u'Peru',u'Peru'),
		(u'Philippines, The',u'Philippines, The'),
		(u'Poland',u'Poland'),
		(u'Portugal',u'Portugal'),
		(u'Qatar',u'Qatar'),
		(u'Romania',u'Romania'),
		(u'Russia',u'Russia'),
		(u'Rwanda',u'Rwanda'),
		(u'St. Kitts and Nevis',u'St. Kitts and Nevis'),
		(u'St. Lucia',u'St. Lucia'),
		(u'St. Vincent and the Grenadines',u'St. Vincent and the Grenadines'),
		(u'Samoa',u'Samoa'),
		(u'San Marino',u'San Marino'),
		(u'Sao Tome and Principe',u'Sao Tome and Principe'),
		(u'Saudi Arabia',u'Saudi Arabia'),
		(u'Scotland',u'Scotland'),
		(u'Senegal',u'Senegal'),
		(u'Seychelles',u'Seychelles'),
		(u'Sierra Leone',u'Sierra Leone'),
		(u'Singapore',u'Singapore'),
		(u'Slovakia',u'Slovakia'),
		(u'Slovenia',u'Slovenia'),
		(u'Solomon Islands',u'Solomon Islands'),
		(u'Somalia',u'Somalia'),
		(u'South Africa',u'South Africa'),
		(u'South Korea',u'South Korea'),
		(u'Spain',u'Spain'),
		(u'Sri Lanka',u'Sri Lanka'),
		(u'Sudan',u'Sudan'),
		(u'Suriname',u'Suriname'),
		(u'Swaziland',u'Swaziland'),
		(u'Sweden',u'Sweden'),
		(u'Switzerland',u'Switzerland'),
		(u'Syria',u'Syria'),
		(u'Taiwan',u'Taiwan'),
		(u'Tajikistan',u'Tajikistan'),
		(u'Tanzania',u'Tanzania'),
		(u'Thailand',u'Thailand'),
		(u'Togo',u'Togo'),
		(u'Tonga',u'Tonga'),
		(u'Trinidad and Tobago',u'Trinidad and Tobago'),
		(u'Tunisia',u'Tunisia'),
		(u'Turkey',u'Turkey'),
		(u'Turkmenistan',u'Turkmenistan'),
		(u'Tuvalu',u'Tuvalu'),
		(u'Uganda',u'Uganda'),
		(u'Ukraine',u'Ukraine'),
		(u'United Arab Emirates',u'United Arab Emirates'),
		(u'United Kingdom',u'United Kingdom'),
		(u'United States',u'United States'),
		(u'Uruguay',u'Uruguay'),
		(u'Uzbekistan',u'Uzbekistan'),
		(u'Vanuatu',u'Vanuatu'),
		(u'Vatican City',u'Vatican City'),
		(u'Venezuela',u'Venezuela'),
		(u'Vietnam',u'Vietnam'),
		(u'Wales',u'Wales'),
		(u'Yemen',u'Yemen'),
		(u'Yugoslavia',u'Yugoslavia'),
		(u'Zambia',u'Zambia'),
		(u'Zimbabwe',u'Zimbabwe')
	)